spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.2.7:9876
        bindings:
          input:
            consumer:
              orderly: true
      bindings:
        input:
          destination: topic-email
          content-type: application/json
          group: group-email
          consumer:
            maxAttempts: 1
server:
  port: 9507