spring:
  cloud:
    sentinel:
      datasource:
        ds:
          nacos:
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            rule-type: flow
            server-addr: 192.168.2.7:8848,192.168.2.7:8849,192.168.2.7:8850
    stream:
      rocketmq:
        binder:
          name-server: 192.168.2.7:9876
      bindings:
        output:
          content-type: application/json
          destination: topic-email
          producer:
            group: group-email
  datasource:
      base:
        #监控统计拦截的filters
        filters: stat
        type: com.alibaba.druid.pool.DruidDataSource
        jdbc-url: jdbc:mysql://192.168.2.7:185/ht_micro_record?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        initial-size: 5
        validation-query: SELECT 1
        test-on-borrow: false
        test-while-idle: true
        time-between-eviction-runs-millis: 18800
      dic:
        #监控统计拦截的filters
        filters: stat
        type: com.alibaba.druid.pool.DruidDataSource
        jdbc-url: jdbc:mysql://192.168.1.48:3306/ht_nlp?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: Sonar@1234
        driver-class-name: com.mysql.jdbc.Driver
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        initial-size: 5
        validation-query: SELECT 1
        test-on-borrow: false
        test-while-idle: true
        time-between-eviction-runs-millis: 18800
  session:
    # session 存储方式 支持redis、mongo、jdbc、hazelcast
    store-type: redis
  redis:
    #    host: 192.168.2.7
    #    port: 6379
    #    jedis:
    #      pool:
    #        # 连接池最大连接数,使用负值表示无限制。
    #        max-active: 8
    #        # 连接池最大阻塞等待时间,使用负值表示无限制。
    #        max-wait: -1s
    #        # 连接池最大空闲数,使用负值表示无限制。
    #        max-idle: 8
    #        # 连接池最小空闲连接，只有设置为正值时候才有效
    #        min-idle: 1
    #    timeout: 300ms
    cluster:
      # 各 Redis 节点信息
      nodes: 192.168.2.5:8001,192.168.2.5:8002,192.168.2.5:8003,192.168.2.7:8004,192.168.2.7:8005,192.168.2.7:8006
      # 执行命令超时时间
      command-timeout: 15000
      # 重试次数
      max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 16
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: true

################################nacos##############################################
#spring:
#  application:
#    name: ht-micro-record-service-user
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.2.7:8848,192.168.2.7:8849,192.168.2.7:8850
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: 192.168.2.7:190
#
#
#server:
#  port: 9506
#
# 进行该项设置，可以通过sentinel访问到该客户端的所有规则
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"