spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.2.7:185/ht_micro_record?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.7:8848,192.168.2.7:8849,192.168.2.7:8850
      config:
        server-addr: 192.168.2.7:8848,192.168.2.7:8849,192.168.2.7:8850

server:
  port: 9701

xxl:
  job:
    executor:
      logpath: logs/xxl-job/jobhandler
      appname: xxl-job-executor
      port: 1234
      logretentiondays: -1
      ip: 192.168.3.233
    admin:
      addresses: http://192.168.2.7:183/xxl-job-admin
    accessToken:
###############################nacos################################
#spring:
#  application:
#    name: ht-micro-record-service-xxl-job
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.2.7:8848,192.168.2.7:8849,192.168.2.7:8850
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: 192.168.2.7:190
#
#
#server:
#  port: 9701
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"